### ISSUE TITLE
Umatrix in the tutorial of Ce

### ISSUE THREAD

**Issue by tayral** [TRIQS/hubbardI#1]
_From @xiaoyukaka on January 21, 2015 3:4_

Dear developers,
I have performed the calculations of Ce employing the Hubbard-I approximation with triqs V1.0. When i import Hubbard-I solver by 
# 'from pytriqs.applications.impurity_solvers.hubbard_I.hubbard_solver import Solver'

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xykk/software/triqs/install_triqs/lib/python2.7/dist-packages/pytriqs/applications/impurity_solvers/hubbard_I/**init**.py", line 26, in <module>
    from hubbard_solver import Solver
  File "/home/xykk/software/triqs/install_triqs/lib/python2.7/dist-packages/pytriqs/applications/impurity_solvers/hubbard_I/hubbard_solver.py", line 24, in <module>
    from pytriqs.applications.dft.U_matrix import Umatrix
# ImportError: cannot import name Umatrix

I can find the U_matrix.py and U_matrix.pyc, but it cannot import.

_Copied from original issue: TRIQS/triqs#179_

**Comment by tayral** [comment]
_From @xiaoyukaka on January 21, 2015 5:34_

I found it's the same reason that I could not complete the test during the installation of Hubbard-I. The error information is provided in /hubbardI/build/test/hubbard_output.err.
 How to solve it?

**Comment by tayral** [comment]
Dear xiaoyukaka,
Please post issues referring to HubbardI in the right place, namely at: https://github.com/TRIQS/hubbardI/issues.
Thanks

**Comment by xiaoyukaka** [comment]
@tayral  so sorry.  I'm a beginner.  thank you for your help.

**Comment by tayral** [comment]
Hi,
You should write U_matrix instead of Umatrix in 

```from pytriqs.applications.dft.U_matrix import Umatrix```

**Comment by parcollet** [comment]
Anyway, the hubbard I should be repackaged in dft_tools,
the test need them.

**Comment by leopo** [comment]
This tutorial is not converted to v. 1.2. Has Hubbard-I itself been ported to 1.2?

**Comment by pseth** [comment]
@leopo I corrected the U_matrix definition in HubbardI, so can someone please test this? The test passes.

Also, is there really need for U_matrix in HubbardI? To fit in with generic solvers, shouldn't we change it to pass in the Hamiltonian and not U/J?

**Comment by Wentzell** [comment]
No longer applies for version 3.0.x. Closing this.
