### ISSUE TITLE
hubbardI-version

### ISSUE THREAD

**Issue by Reyhanehe** [TRIQS/hubbardI#10]
Dear all,
 I encountered two installation issues with the most recent versions of the library and of the Hubbard-I solver.
CMake Error at CMakeLists.txt:26 (message):
  The application version is not compatible with the TRIQS library (TRIQS
  library version: 2.0.103 while this application version: 1.4)
 can you help me to fix it?
thank you very much
Reyhaneh

**Comment by leopo** [comment]
Hubbard-I has not yet been ported to v. 2.0 of TRIQS. 
It works with the previous version, 1.4.

**Comment by Reyhanehe** [comment]
Dear leopo
thanks for your comment
But in triqs site the packages with version 1.4 are not accessible.
Can we download them with anoter ways?
Sincerely yours
Reyhaneh
