### ISSUE TITLE
Two installation issues

### ISSUE THREAD

**Issue by krivenko** [TRIQS/hubbardI#3]
Dear Leonid,
I encountered two installation issues with the most recent versions of the library and of the Hubbard-I solver.
First, cmake complains about incompatible version numbers:
```
CMake Error at CMakeLists.txt:26 (message):
  The application version is not compatible with the TRIQS library (TRIQS
  library version: 1.2 while this application version: 1.0)
```
Second, the test phase fails. Did you forget to update the reference HDF file?

**Comment by leopo** [comment]
Hi Igor, I have just fixed these issues. Can you try now?

**Comment by krivenko** [comment]
Thank you, both issues are fixed.
