### ISSUE TITLE
Ce-gamma.py,  Ce-gamma.py  -----  NameError: name 'sigma_mix' is not defined

### ISSUE THREAD

**Issue by Joser1015** [TRIQS/hubbardI#4]
Dear Developer

I am running the Ce-gamma.py download on this web:
http://ipht.cea.fr/triqs/applications/dft_tools/guide/dftdmft_singleshot.html

I has the following error. Could anyone give me instruction? 

The ground state has occupancy  1 and energy     -2.673204
Transitions from     14 atomic states are included in GF
Z =     11.590323

Atomic occupancy  :     1.00000

Atomic mag. mom.  :    -0.00000

Start GF calculations

Checking Sigma for convergence...
Using tolerance 0.0001
Solver has not yet converged
Traceback (most recent call last):
  File "dft_dmft_hubbardI.py", line 92, in <module>
    if (mpi.is_master_node() and (sigma_mix<1.0)):
NameError: name 'sigma_mix' is not defined

Best regards.
Riping Wang
2016.2.12

**Comment by leopo** [comment]
Hello,

Perhaps those examples have not been updated for ver. 1.4 yet. will be checked

**Comment by Joser1015** [comment]
Dear leopo

yes, I tried to add  sigma_mix = 1.0 to the Ce-gamma.py. The previous problem is solved, but there is another parameter not defined. 

Could you please teach me ,or provide me updated Ce-gamma.py. Thank you very much.

The error now is:


    Total Density = 3.999999;Chemical Potential = 0.138859
Trace of Density Matrix: {'down': (1.9999994922175142+3.7675817324577042e-17j), 'up': (1.9999994922175155+1.5270079940833522e-16j)}
Traceback (most recent call last):
  File "dft_dmft_hubbardI.py", line 149, in <module>
    correnerg -= DCenerg[0]
NameError: name 'DCenerg' is not defined



Best regards.
Riping Wang
2016.2.12

**Comment by leopo** [comment]
The HubI solver has been updated today
Please try to rerun with the script 

https://triqs.ipht.cnrs.fr/1.4/applications/dft_tools/guide/images_scripts/Ce-gamma_script.html#ce-gamma-script

from the HubI tutorial

https://triqs.ipht.cnrs.fr/1.4/applications/dft_tools/guide/full_tutorial.html#dmft-setup-hubbard-i-calculations-in-triqs

it should run OK with v. 1.4.

**Comment by Joser1015** [comment]
Dear Leopo,

Thank you very much. I used your new Ce-gamma.py file, it works. However, there are some other problems. After I describe my problems, I have questions at the end of this message. 

After I run “ mpirun -np 64 pytriqs Ce-gamma.py “
I then continue to run 
Run_lapw –qdmft 1 –cc -.001 –NI  > run_dftdmft.out  

The programing was running, but during the running, it repeated to report that as the following.

[riping@fermi Ce-gamma]$ run_lapw   -qdmft  1   -cc 0.001 -NI  > run_dftdmft.out
 LAPW0 END
 LAPW1 END
 LAPW2 END
python_with_DMFT: Command not found.
 LAPW2 END
 CORE  END
 MIXER END
 LAPW0 END
 LAPW1 END
 LAPW2 END
python_with_DMFT: Command not found.
 LAPW2 END
 CORE  END
 MIXER END
 LAPW0 END
 LAPW1 END
 LAPW2 END
python_with_DMFT: Command not found.
 LAPW2 END
 CORE  END
 MIXER END
 LAPW0 END
 LAPW1 END
 LAPW2 END
python_with_DMFT: Command not found.



And there is “stop error” at the end of the program. I printed the ending lines of run_lapw_dfmt.out as bellow.
-------------------------------------
Density Matrices for the Correlated States :

  Sort =   1  Atom =   1  and Orbital l =   3

    0.110842    0.000000   -0.000000   -0.000000    0.000000    0.000000   -0.000000   -0.000000    0.061018    0.000000    0.000000    0.000000    0.000000    0.000000
   -0.000000    0.000000    0.162250    0.000000    0.000000    0.000000    0.000000   -0.000000    0.000000    0.000000   -0.130182   -0.000000   -0.000000   -0.000000
    0.000000   -0.000000    0.000000   -0.000000    0.079332    0.000000   -0.000000    0.000000    0.000000   -0.000000   -0.000000   -0.000000    0.061018    0.000000
   -0.000000    0.000000    0.000000    0.000000   -0.000000   -0.000000    0.158106    0.000000    0.000000   -0.000000    0.000000   -0.000000    0.000000    0.000000
    0.061018   -0.000000    0.000000   -0.000000    0.000000    0.000000    0.000000    0.000000    0.079332   -0.000000   -0.000000   -0.000000    0.000000    0.000000
    0.000000   -0.000000   -0.130182    0.000000   -0.000000    0.000000    0.000000    0.000000   -0.000000    0.000000    0.162250   -0.000000    0.000000    0.000000
    0.000000   -0.000000   -0.000000    0.000000    0.061018   -0.000000    0.000000   -0.000000    0.000000   -0.000000    0.000000   -0.000000    0.110842   -0.000000

The charge of the orbital is :    0.86295
Writing the file case.ctqmcout...
Writing the file case.symqmc...
Writing the file case.parproj...
Writing the file case.sympar...
Writing the file case.outbwin...

END OF THE PRGM

>   stop error




Therefore, my questions:
1.	What is the reason for it to complain that “python_with_DMFT: Command not found”?
2.	Why does it report “stop error”?
3.	Before I run run_lapws, do I must run a single DFT_DMFT calculation?

Riping Wang
2016.2.13

**Comment by Joser1015** [comment]
Dear Leopo,

I passed the error of “python_with_DMFT: Command not found”, following the instruction in the installation page of DFTTools : https://triqs.ipht.cnrs.fr/1.3/applications/dft_tools/install.html. 

Thank you very much.

Riping Wang
 2016.2.18

**Comment by Wentzell** [comment]
This issue is outdated and does not apply for version 3.0.x. Closing this.
